# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
      - main
      - "release-*"
    # Publish semver tags as releases.
    tags: ["v*.*.*"]
    paths-ignore:
      - "*.md"
  pull_request:
    branches:
      - "main"
    paths-ignore:
      - "*.md"

env:
  IMAGE_NAME: ${{ github.repository }}
  GONOPROXY: kubegems.io

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
      - name: Plugin Cache
        uses: actions/cache@v2
        with:
          path: |
            bin/plugins
          key: plugins-${{ hashFiles('deploy/plugins/**') }}
          restore-keys: plugins-

      # Build binary
      - name: Build binaries
        env:
          GIT_VERSION: ${{ github.ref_name }}
        run: make build

      # Build images
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2
        id: buildx
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2.0.0
        with:
          registry: ${{ secrets.REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Log into registry ${{ env.SECONDARY_REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2.0.0
        with:
          registry: ${{ secrets.SECONDARY_REGISTRY }}
          username: ${{ secrets.SECONDARY_REGISTRY_USERNAME }}
          password: ${{ secrets.SECONDARY_REGISTRY_PASSWORD }}
      - uses: azure/setup-helm@v3
        if: startsWith(github.ref, 'refs/tags/v')
      - name: Make Helm Release on tag
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          GIT_VERSION: ${{ github.ref_name }}
          HELM_REPO_PASSWORD: ${{ secrets.HELM_REPO_PASSWORD }}
        run: make helm-release
      - name: Make Image Release
        if: github.event_name != 'pull_request'
        env:
          GIT_VERSION: ${{ github.ref_name }}
        run: make image-release
